/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/departments": {
    get: operations["list_depts"];
    post: operations["create_dept"];
  };
  "/departments/{id}": {
    get: operations["get_dept"];
    delete: operations["delete_dept"];
    patch: operations["update_dept"];
  };
  "/groups": {
    get: operations["list_groups"];
    post: operations["create_group"];
  };
  "/groups/{id}": {
    get: operations["get_group"];
    delete: operations["delete_group"];
    patch: operations["update_group"];
  };
  "/groups/{id}/messages": {
    /** The full message history for a group, oldest first. */
    get: operations["list_messages"];
    /**
     * Posts a user message and kicks off the agents' turn. The returned line is the
     * stored user message; AI replies, moods, and read receipts arrive on the
     * group's SSE stream.
     */
    post: operations["send_message"];
  };
  "/groups/{id}/stream": {
    /**
     * Server-Sent Events for a group: default `message` events (AI replies and
     * moods) and named `read` events (read receipts).
     */
    get: operations["stream"];
  };
  "/health": {
    /** Liveness probe. */
    get: operations["health"];
  };
  "/organizations": {
    get: operations["list_orgs"];
    post: operations["create_org"];
  };
  "/organizations/{id}": {
    get: operations["get_org"];
    delete: operations["delete_org"];
    patch: operations["update_org"];
  };
  "/personas": {
    get: operations["list_personas"];
    post: operations["create_persona"];
  };
  "/personas/{id}": {
    get: operations["get_persona"];
    /**
     * Deletes a persona. Refuses (409) to remove the last remaining user identity,
     * since every group still needs a "you".
     */
    delete: operations["delete_persona"];
    patch: operations["update_persona"];
  };
  "/settings": {
    get: operations["get_settings"];
    patch: operations["update_settings"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description A sub-unit inside an organization; its variables sit between the org's and
     * the persona's in the inheritance chain.
     */
    Department: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name: string;
      organizationId: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description A chat room: the AI personas that may speak, plus the user identity that
     * represents "you" here.
     */
    Group: {
      id?: string;
      name: string;
      personaIds: string[];
      selfPersonaId: string;
    };
    /** @description One chat line. Tagged by `kind`, matching the TypeScript `Message` union. */
    Message: OneOf<[{
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "conversation";
      personaId: string;
      /** @description AI persona ids that have successfully processed (read) this message. */
      readBy?: string[] | null;
      streaming?: boolean | null;
      text: string;
      /** Format: int64 */
      ts: number;
    }, {
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "mood";
      mood: string;
      note?: string | null;
      personaId: string;
      /** Format: int64 */
      ts: number;
    }]>;
    /**
     * @description A bucket for classifying personas that also carries shared template
     * variables its members inherit.
     */
    Organization: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description A user identity or an AI agent. AI personas carry the system prompt and
     * variables the model needs; user personas are just a "you" to speak as.
     */
    Persona: {
      avatarUrl?: string | null;
      blurb?: string | null;
      color: string;
      departmentId?: string | null;
      emoji?: string | null;
      gradient?: string | null;
      id?: string;
      kind: components["schemas"]["PersonaKind"];
      name: string;
      organizationId?: string | null;
      systemPrompt?: string | null;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description The two persona roles: a user's own identity vs. an AI agent.
     * @enum {string}
     */
    PersonaKind: "user" | "ai";
    /**
     * @description A single AI persona acknowledging it successfully processed a message —
     * whether or not it chose to reply (agents may read without replying).
     */
    ReadReceipt: {
      groupId: string;
      messageId: string;
      personaId: string;
    };
    /** @description The body of a send request. */
    SendBody: {
      /** @description The message text to post as the group's current "you" identity. */
      text: string;
    };
    /** @description User-level preferences. */
    Settings: {
      /** Format: int32 */
      chatFontSize: number;
      nativeLanguage: string;
      uiLanguage: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  list_depts: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Department"][];
        };
      };
    };
  };
  create_dept: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Department"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
    };
  };
  get_dept: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  delete_dept: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      204: {
        content: never;
      };
      404: {
        content: never;
      };
    };
  };
  update_dept: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Department"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  list_groups: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"][];
        };
      };
    };
  };
  create_group: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Group"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
    };
  };
  get_group: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  delete_group: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      204: {
        content: never;
      };
      404: {
        content: never;
      };
    };
  };
  update_group: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Group"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  /** The full message history for a group, oldest first. */
  list_messages: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    responses: {
      /** @description Message history */
      200: {
        content: {
          "application/json": components["schemas"]["Message"][];
        };
      };
    };
  };
  /**
   * Posts a user message and kicks off the agents' turn. The returned line is the
   * stored user message; AI replies, moods, and read receipts arrive on the
   * group's SSE stream.
   */
  send_message: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendBody"];
      };
    };
    responses: {
      /** @description The stored user message */
      200: {
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      /** @description Unknown group */
      404: {
        content: never;
      };
    };
  };
  /**
   * Server-Sent Events for a group: default `message` events (AI replies and
   * moods) and named `read` events (read receipts).
   */
  stream: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    responses: {
      /** @description text/event-stream: `message` frames carry a Message, `read` frames carry a ReadReceipt */
      200: {
        content: never;
      };
    };
  };
  /** Liveness probe. */
  health: {
    responses: {
      /** @description Service is up */
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  list_orgs: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Organization"][];
        };
      };
    };
  };
  create_org: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  get_org: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  delete_org: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Deleted (cascades to its departments) */
      204: {
        content: never;
      };
      404: {
        content: never;
      };
    };
  };
  update_org: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  list_personas: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Persona"][];
        };
      };
    };
  };
  create_persona: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Persona"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
    };
  };
  get_persona: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  /**
   * Deletes a persona. Refuses (409) to remove the last remaining user identity,
   * since every group still needs a "you".
   */
  delete_persona: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      204: {
        content: never;
      };
      404: {
        content: never;
      };
      /** @description Refused: last remaining user identity */
      409: {
        content: never;
      };
    };
  };
  update_persona: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Persona"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  get_settings: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  update_settings: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Settings"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
      422: {
        content: never;
      };
    };
  };
}
