/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/debug/usage": {
    /**
     * Cumulative LLM usage since startup — the global "total usage" readout:
     * request count, token breakdown, cache-hit ratio, and an estimated cost when
     * pricing is configured (always an estimate, for reference only).
     */
    get: operations["debug_usage"];
  };
  "/departments": {
    get: operations["list_depts"];
    post: operations["create_dept"];
  };
  "/departments/{id}": {
    get: operations["get_dept"];
    delete: operations["delete_dept"];
    patch: operations["update_dept"];
  };
  "/groups": {
    get: operations["list_groups"];
    post: operations["create_group"];
  };
  "/groups/{id}": {
    get: operations["get_group"];
    delete: operations["delete_group"];
    patch: operations["update_group"];
  };
  "/groups/{id}/debug/traces": {
    /**
     * Recent agent traces for a group — the exact prompt each character received
     * and what it decided — for hydrating the debug panel. Live updates then arrive
     * as `debug` SSE frames on the group stream.
     */
    get: operations["debug_traces"];
  };
  "/groups/{id}/events": {
    /**
     * Posts an environment event into a group — rain, time passing, an emergency —
     * letting the world outside the chat influence the agents. Accepted and queued
     * for the group's coordinator; its effect (reactions, moods) arrives on the
     * group's SSE stream.
     */
    post: operations["post_event"];
  };
  "/groups/{id}/messages": {
    /** The full message history for a group, oldest first. */
    get: operations["list_messages"];
    /**
     * Posts a user message and kicks off the agents' turn. The returned line is the
     * stored user message; AI replies, moods, and read receipts arrive on the
     * group's SSE stream.
     */
    post: operations["send_message"];
  };
  "/groups/{id}/retry": {
    /**
     * Resumes a turn that was suspended by a failed agent inference: the agents who
     * have not yet read the pending message respond to the current chat. A no-op if
     * nothing is suspended (e.g. the pending turn was already voided by a newer
     * message). Its effect arrives on the group's SSE stream.
     */
    post: operations["retry_turn"];
  };
  "/groups/{id}/stream": {
    /**
     * Server-Sent Events for a group: default `message` events (AI replies and
     * moods), named `read` events (read receipts), and named `activity` events
     * (the agent loop turning busy/idle).
     */
    get: operations["stream"];
  };
  "/health": {
    /** Liveness probe — cheap "is the server up" check. */
    get: operations["health"];
  };
  "/meta": {
    /**
     * The server's mode, so the client can distinguish a mock build (no LLM,
     * in-memory) from a production one — separately from mere reachability.
     */
    get: operations["meta"];
  };
  "/organizations": {
    get: operations["list_orgs"];
    post: operations["create_org"];
  };
  "/organizations/{id}": {
    get: operations["get_org"];
    delete: operations["delete_org"];
    patch: operations["update_org"];
  };
  "/personas": {
    get: operations["list_personas"];
    /**
     * Creates a persona. Rejects (409) a duplicate name (names are globally unique)
     * or a second user identity (there is only ever one "you").
     */
    post: operations["create_persona"];
  };
  "/personas/{id}": {
    get: operations["get_persona"];
    /**
     * Deletes a persona. Refuses (409) to remove the last remaining user identity,
     * since every group still needs a "you".
     */
    delete: operations["delete_persona"];
    /**
     * Updates a persona. 404 for an unknown id; 409 for a duplicate name or a change
     * that would produce a second user identity.
     */
    patch: operations["update_persona"];
  };
  "/prompt-labels": {
    /**
     * All user-assigned names for persona identity hashes. The memory UI reads this
     * to show a friendly label (e.g. "bar 版") next to a persona's prompt version.
     */
    get: operations["list_prompt_labels"];
  };
  "/prompt-labels/{hash}": {
    /**
     * Names an identity hash, or clears its name when the label is blank. Idempotent
     * (PUT), keyed by the full hash the client already holds from the persona.
     */
    put: operations["set_prompt_label"];
  };
  "/settings": {
    get: operations["get_settings"];
    patch: operations["update_settings"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description A debug record of one agent inference: exactly the system + context the
     * character's model received, what it decided, and the tokens it cost. Streamed
     * live as a `debug` SSE frame and available in bulk for panel hydration.
     */
    AgentTrace: {
      /** @description The chosen action: `speak` | `speakWithMood` | `mood` | `read`. */
      action: string;
      /** @description The conversation/context text the agent read (the "public" messages). */
      conversation: string;
      groupId: string;
      /** @description The spoken line, when it spoke. */
      message?: string | null;
      /** @description The mood, when it showed one. */
      mood?: string | null;
      personaId: string;
      personaName: string;
      /** @description The full system prompt the agent got (persona + variables + roster). */
      system: string;
      /** Format: int64 */
      ts: number;
      usage?: null | components["schemas"]["TokenUsage"];
    };
    /**
     * @description An estimated cost breakdown for the accumulated usage. Always an estimate:
     * rates are operator-supplied and providers/models differ, so the UI labels it
     * "for reference only".
     */
    Cost: {
      /**
       * Format: double
       * @description Cost of cached input tokens.
       */
      cachedInput: number;
      /** @description Currency label the rates are in (e.g. `USD`). */
      currency: string;
      /**
       * Format: double
       * @description Cost of fresh (non-cached) input tokens.
       */
      input: number;
      /**
       * Format: double
       * @description Cost of output tokens.
       */
      output: number;
      /**
       * Format: double
       * @description Sum of the above.
       */
      total: number;
    };
    /**
     * @description Cumulative LLM usage across the whole server since startup — the global
     * "total usage" view. `GET /debug/usage`.
     */
    DebugUsage: {
      /**
       * Format: double
       * @description Cached prompt tokens ÷ prompt tokens, in `0.0..=1.0`; `0` before any
       * usage is seen. How much the cache is saving.
       */
      cacheHitRatio: number;
      /** Format: int64 */
      cachedPromptTokens: number;
      /** Format: int64 */
      completionTokens: number;
      estimatedCost?: null | components["schemas"]["Cost"];
      /** Format: int64 */
      promptTokens: number;
      /**
       * Format: int64
       * @description Number of agent inferences (LLM requests in LLM mode).
       */
      requests: number;
      /** Format: int64 */
      totalTokens: number;
    };
    /**
     * @description A sub-unit inside an organization; its variables sit between the org's and
     * the persona's in the inheritance chain.
     */
    Department: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name: string;
      organizationId: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /** @description The body of an environment-event request. */
    EventBody: {
      /** @description A short description of what changed, e.g. "It starts to rain." */
      description: string;
      /**
       * @description Urgent events preempt the current turn (discarding the in-flight agent);
       * ordinary ones fold into the context at the next agent boundary.
       */
      urgent?: boolean;
    };
    /**
     * @description A chat room: the AI personas that may speak, plus the user identity that
     * represents "you" here.
     */
    Group: {
      id?: string;
      name: string;
      personaIds: string[];
      selfPersonaId: string;
    };
    /** @description One chat line. Tagged by `kind`, matching the TypeScript `Message` union. */
    Message: OneOf<[{
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "conversation";
      personaId: string;
      /** @description AI persona ids that have successfully processed (read) this message. */
      readBy?: string[] | null;
      streaming?: boolean | null;
      text: string;
      /** Format: int64 */
      ts: number;
    }, {
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "mood";
      mood: string;
      note?: string | null;
      personaId: string;
      /** Format: int64 */
      ts: number;
    }, {
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "system";
      personaId: string;
      /**
       * @description The status's canonical reason (e.g. "Too Many Requests"), or a short
       * generic label for a transport failure with no status.
       */
      reason: string;
      /**
       * Format: int32
       * @description The HTTP status code, when the failure carried one (e.g. 429).
       */
      status?: number | null;
      /** Format: int64 */
      ts: number;
    }]>;
    /**
     * @description A bucket for classifying personas that also carries shared template
     * variables its members inherit.
     */
    Organization: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description A user identity or an AI agent. AI personas carry the system prompt and
     * variables the model needs; user personas are just a "you" to speak as.
     */
    Persona: {
      avatarUrl?: string | null;
      blurb?: string | null;
      color: string;
      departmentId?: string | null;
      emoji?: string | null;
      gradient?: string | null;
      id?: string;
      kind: components["schemas"]["PersonaKind"];
      name: string;
      organizationId?: string | null;
      /**
       * @description Content hash of the raw `system_prompt` template — the persona's identity
       * "version". Server-computed and effectively read-only on the wire: it is
       * recomputed on every create/update (and on load) and any value a client
       * sends is ignored. `None` when there is no prompt (user identities). Full
       * lowercase-hex SHA-256; the UI shows a truncated prefix. See [`prompt_hash`].
       */
      promptHash?: string | null;
      systemPrompt?: string | null;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description The two persona roles: a user's own identity vs. an AI agent.
     * @enum {string}
     */
    PersonaKind: "user" | "ai";
    /**
     * @description A user-assigned, git-tag-style name for a persona identity hash
     * ([`Persona::prompt_hash`]). Held in a side table so naming a version never
     * mutates the persona itself; content-addressing means reverting to earlier
     * exact prompt text resolves back to the same (possibly already-named) hash.
     */
    PromptLabel: {
      hash: string;
      label: string;
    };
    /** @description Request body for naming a prompt identity hash. A blank label clears the name. */
    PromptLabelInput: {
      label: string;
    };
    /**
     * @description A single AI persona acknowledging it successfully processed a message —
     * whether or not it chose to reply (agents may read without replying).
     */
    ReadReceipt: {
      groupId: string;
      messageId: string;
      personaId: string;
    };
    /** @description The body of a send request. */
    SendBody: {
      /**
       * @description The "you" identity to author the message as. When omitted, the group's
       * stored `selfPersonaId` is used.
       */
      personaId?: string | null;
      /** @description The message text. */
      text: string;
    };
    /**
     * @description What the running server offers — lets the client tell a mock build (no LLM,
     * in-memory only) apart from a production one, independently of whether the
     * server is reachable at all.
     */
    ServerMeta: {
      /** @description An LLM is wired in to generate replies. */
      llm: boolean;
      /**
       * @description No LLM and no persistence — the "mock" mode. Equivalent to
       * `!llm && !persistent`.
       */
      mock: boolean;
      /** @description State is persisted and survives a restart. */
      persistent: boolean;
      /** @description Server crate version. */
      version: string;
    };
    /** @description User-level preferences. */
    Settings: {
      /** Format: int32 */
      chatFontSize: number;
      nativeLanguage: string;
      uiLanguage: string;
    };
    /**
     * @description Token usage for one LLM inference. Zero across the board when the provider
     * reports nothing; entirely absent (on the trace) for the rule-based mock,
     * which makes no LLM call.
     */
    TokenUsage: {
      /**
       * Format: int64
       * @description Of the prompt tokens, how many were served from the provider's cache —
       * billed cheaper. The basis for the cache-hit ratio and cache savings.
       */
      cachedPromptTokens: number;
      /**
       * Format: int64
       * @description Output ("completion") tokens billed for this call.
       */
      completionTokens: number;
      /**
       * Format: int64
       * @description Input ("prompt") tokens billed for this call.
       */
      promptTokens: number;
      /**
       * Format: int64
       * @description Total tokens the provider reported (or input+output when it only gives
       * the two).
       */
      totalTokens: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Cumulative LLM usage since startup — the global "total usage" readout:
   * request count, token breakdown, cache-hit ratio, and an estimated cost when
   * pricing is configured (always an estimate, for reference only).
   */
  debug_usage: {
    responses: {
      /** @description Cumulative LLM usage */
      200: {
        content: {
          "application/json": components["schemas"]["DebugUsage"];
        };
      };
    };
  };
  list_depts: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Department"][];
        };
      };
    };
  };
  create_dept: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Department"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
    };
  };
  get_dept: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  delete_dept: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      204: {
        content: never;
      };
      404: {
        content: never;
      };
    };
  };
  update_dept: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Department"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  list_groups: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"][];
        };
      };
    };
  };
  create_group: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Group"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
    };
  };
  get_group: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  delete_group: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      204: {
        content: never;
      };
      404: {
        content: never;
      };
    };
  };
  update_group: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Group"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  /**
   * Recent agent traces for a group — the exact prompt each character received
   * and what it decided — for hydrating the debug panel. Live updates then arrive
   * as `debug` SSE frames on the group stream.
   */
  debug_traces: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    responses: {
      /** @description Recent agent traces, oldest first */
      200: {
        content: {
          "application/json": components["schemas"]["AgentTrace"][];
        };
      };
    };
  };
  /**
   * Posts an environment event into a group — rain, time passing, an emergency —
   * letting the world outside the chat influence the agents. Accepted and queued
   * for the group's coordinator; its effect (reactions, moods) arrives on the
   * group's SSE stream.
   */
  post_event: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventBody"];
      };
    };
    responses: {
      /** @description Event accepted */
      202: {
        content: never;
      };
      /** @description Unknown group */
      404: {
        content: never;
      };
    };
  };
  /** The full message history for a group, oldest first. */
  list_messages: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    responses: {
      /** @description Message history */
      200: {
        content: {
          "application/json": components["schemas"]["Message"][];
        };
      };
    };
  };
  /**
   * Posts a user message and kicks off the agents' turn. The returned line is the
   * stored user message; AI replies, moods, and read receipts arrive on the
   * group's SSE stream.
   */
  send_message: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendBody"];
      };
    };
    responses: {
      /** @description The stored user message */
      200: {
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      /** @description Unknown group */
      404: {
        content: never;
      };
    };
  };
  /**
   * Resumes a turn that was suspended by a failed agent inference: the agents who
   * have not yet read the pending message respond to the current chat. A no-op if
   * nothing is suspended (e.g. the pending turn was already voided by a newer
   * message). Its effect arrives on the group's SSE stream.
   */
  retry_turn: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    responses: {
      /** @description Retry accepted */
      202: {
        content: never;
      };
      /** @description Unknown group */
      404: {
        content: never;
      };
    };
  };
  /**
   * Server-Sent Events for a group: default `message` events (AI replies and
   * moods), named `read` events (read receipts), and named `activity` events
   * (the agent loop turning busy/idle).
   */
  stream: {
    parameters: {
      path: {
        /** @description Group id */
        id: string;
      };
    };
    responses: {
      /** @description text/event-stream: `message` frames carry a Message, `read` frames carry a ReadReceipt, `activity` frames carry `{ active: bool }`, `debug` frames carry an AgentTrace */
      200: {
        content: never;
      };
    };
  };
  /** Liveness probe — cheap "is the server up" check. */
  health: {
    responses: {
      /** @description Service is up */
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  /**
   * The server's mode, so the client can distinguish a mock build (no LLM,
   * in-memory) from a production one — separately from mere reachability.
   */
  meta: {
    responses: {
      /** @description Server capabilities */
      200: {
        content: {
          "application/json": components["schemas"]["ServerMeta"];
        };
      };
    };
  };
  list_orgs: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Organization"][];
        };
      };
    };
  };
  create_org: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  get_org: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  delete_org: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Deleted (cascades to its departments) */
      204: {
        content: never;
      };
      404: {
        content: never;
      };
    };
  };
  update_org: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  list_personas: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Persona"][];
        };
      };
    };
  };
  /**
   * Creates a persona. Rejects (409) a duplicate name (names are globally unique)
   * or a second user identity (there is only ever one "you").
   */
  create_persona: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Persona"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      /** @description Refused: name already in use, or a second user identity */
      409: {
        content: never;
      };
    };
  };
  get_persona: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      404: {
        content: never;
      };
    };
  };
  /**
   * Deletes a persona. Refuses (409) to remove the last remaining user identity,
   * since every group still needs a "you".
   */
  delete_persona: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      204: {
        content: never;
      };
      404: {
        content: never;
      };
      /** @description Refused: last remaining user identity */
      409: {
        content: never;
      };
    };
  };
  /**
   * Updates a persona. 404 for an unknown id; 409 for a duplicate name or a change
   * that would produce a second user identity.
   */
  update_persona: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Persona"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      404: {
        content: never;
      };
      /** @description Refused: name already in use, or a second user identity */
      409: {
        content: never;
      };
    };
  };
  /**
   * All user-assigned names for persona identity hashes. The memory UI reads this
   * to show a friendly label (e.g. "bar 版") next to a persona's prompt version.
   */
  list_prompt_labels: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PromptLabel"][];
        };
      };
    };
  };
  /**
   * Names an identity hash, or clears its name when the label is blank. Idempotent
   * (PUT), keyed by the full hash the client already holds from the persona.
   */
  set_prompt_label: {
    parameters: {
      path: {
        hash: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromptLabelInput"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PromptLabel"];
        };
      };
    };
  };
  get_settings: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  update_settings: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Settings"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
      422: {
        content: never;
      };
    };
  };
}
