/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/v1beta/accounts": {
    /** Every existing account, for the admin dashboard's account list. */
    get: operations["list_accounts"];
    /**
     * Provisions a brand-new account with an admin-chosen username and
     * password. There's no self-service registration — this is the only way an
     * account gets created.
     */
    post: operations["create_account"];
  };
  "/v1beta/accounts/{accountId}": {
    /**
     * Changes an existing account's username, password, or both. Every live
     * session for that account is revoked: its tokens stop working immediately and
     * the holder must sign in again.
     */
    patch: operations["update_account"];
  };
  "/v1beta/auth/login": {
    /**
     * Logs in as the admin (username `"admin"`) or a regular account (its own
     * stored username). An account with no fixed password yet accepts this
     * boot's generated one instead — see the server log at startup.
     */
    post: operations["login"];
  };
  "/v1beta/auth/logout": {
    /**
     * Ends the current session: the presented access token (from the
     * `Authorization` header) and refresh token stop working immediately.
     */
    post: operations["logout"];
  };
  "/v1beta/auth/refresh": {
    /**
     * Mints a fresh access token from a still-valid refresh token, without
     * asking for the password again. The refresh token itself is not rotated —
     * it keeps working until its own (much longer) expiry.
     */
    post: operations["refresh"];
  };
  "/v1beta/departments": {
    /** Every department in the workspace, across all organizations. */
    get: operations["list_depts"];
    /** Creates a department. */
    post: operations["create_dept"];
  };
  "/v1beta/departments/{departmentId}": {
    /** One department by id. */
    get: operations["get_dept"];
    /** Deletes a department. */
    delete: operations["delete_dept"];
    /** Merges a partial update onto a department. */
    patch: operations["update_dept"];
  };
  "/v1beta/groups": {
    /** Every chat group in the workspace. */
    get: operations["list_groups"];
    /** Creates a group. */
    post: operations["create_group"];
  };
  "/v1beta/groups/{groupId}": {
    /** One group by id. */
    get: operations["get_group"];
    /** Deletes a group. */
    delete: operations["delete_group"];
    /** Merges a partial update onto a group. */
    patch: operations["update_group"];
  };
  "/v1beta/groups/{groupId}/events": {
    /**
     * Posts an environment event — rain, time passing, an emergency — letting the
     * world outside the chat influence the agents. Its effect arrives on the SSE
     * stream.
     */
    post: operations["post_event"];
  };
  "/v1beta/groups/{groupId}/messages": {
    /**
     * A contiguous window of message history, oldest first. Max 500 lines (160
     * without an `anchor`).
     */
    get: operations["list_messages"];
    /**
     * Posts a user message and starts the agents' turn. Replies, moods, and read
     * receipts arrive on the SSE stream.
     */
    post: operations["send_message"];
  };
  "/v1beta/groups/{groupId}/retry": {
    /**
     * Resumes a turn suspended by a failed agent inference. A no-op if nothing is
     * suspended. Its effect arrives on the SSE stream.
     */
    post: operations["retry_turn"];
  };
  "/v1beta/groups/{groupId}/stream": {
    /**
     * Server-Sent Events for a group.
     * @description Frames: unnamed = `Message`; `read` = `ReadReceipt`; `activity` =
     * `{ "active": bool }`; `turn` = `Turn`; `debug` = `AgentTrace`;
     * `suggestions` = `GroupSuggestions`. `activity` and `turn` are seeded on connect.
     */
    get: operations["stream"];
  };
  "/v1beta/groups/{groupId}/suggestions": {
    /**
     * Cached conversation-starter suggestions, served from the server-side cache.
     * Empty (`generatedAt == 0`) until the first generation completes.
     */
    get: operations["get_suggestions"];
    /**
     * Creates a fresh set of suggestions (the composer's "give me other ideas").
     * Generated in the background; the result arrives on the `suggestions` SSE
     * frame. Rate-limited server-side — repeated calls coalesce.
     */
    post: operations["regenerate_suggestions"];
  };
  "/v1beta/groups/{groupId}/traces": {
    /**
     * Recent agent traces: the prompt each character received and what it decided.
     * Live updates arrive as `debug` SSE frames.
     */
    get: operations["list_traces"];
  };
  "/v1beta/health": {
    /** Liveness probe, for an orchestrator rather than the app. */
    get: operations["health"];
  };
  "/v1beta/llm/models": {
    /**
     * Lists the models a provider endpoint offers, so the model field can be a
     * picker. Admin-only. `apiKey` is required unless `baseUrl` matches the
     * already-configured endpoint.
     */
    post: operations["list_llm_models"];
  };
  "/v1beta/llm/settings": {
    /**
     * The live LLM provider configuration. Any signed-in caller may read it;
     * `canEdit` says whether this caller may write it.
     */
    get: operations["get_llm_settings"];
    /**
     * Merges a partial update onto the LLM provider configuration and applies it
     * immediately. Admin-only.
     */
    patch: operations["update_llm_settings"];
  };
  "/v1beta/meta": {
    /** The server's mode: mock build (no LLM, in-memory) vs. production. */
    get: operations["meta"];
  };
  "/v1beta/organizations": {
    /** Every organization in the workspace. */
    get: operations["list_orgs"];
    /** Creates an organization. */
    post: operations["create_org"];
  };
  "/v1beta/organizations/{organizationId}": {
    /** One organization by id. */
    get: operations["get_org"];
    /** Deletes an organization, cascading to its departments. */
    delete: operations["delete_org"];
    /** Merges a partial update onto an organization. */
    patch: operations["update_org"];
  };
  "/v1beta/personas": {
    /** Every persona in the workspace — the one user identity and every AI agent. */
    get: operations["list_personas"];
    /**
     * Creates a persona. Names are globally unique, and there is only ever one
     * user identity ("you"), so either collision is refused with 409.
     */
    post: operations["create_persona"];
  };
  "/v1beta/personas/{personaId}": {
    /** One persona by id. */
    get: operations["get_persona"];
    /**
     * Deletes a persona. The last remaining user identity can't go — every group
     * still needs a "you".
     */
    delete: operations["delete_persona"];
    /**
     * Merges a partial update onto a persona. `promptHash` is recomputed from the
     * resulting prompt; any value sent for it is ignored.
     */
    patch: operations["update_persona"];
  };
  "/v1beta/personas/{personaId}/memories": {
    /**
     * Every memory a persona has accumulated, across all of its identity versions,
     * newest first. The memory-management UI groups the result by `promptHash`/label.
     */
    get: operations["list_memories"];
    /** Writes a memory for a persona, tagged with its current identity hash. */
    post: operations["create_memory"];
  };
  "/v1beta/personas/{personaId}/memories/{memoryId}": {
    /** Deletes one of a persona's memories. */
    delete: operations["delete_memory"];
  };
  "/v1beta/preferences": {
    /** The signed-in account's own display preferences. */
    get: operations["get_preferences"];
    /** Merges a partial update onto the account's preferences. */
    patch: operations["update_preferences"];
  };
  "/v1beta/prompt-labels": {
    /**
     * All user-assigned names for persona identity hashes. The memory UI reads this
     * to show a friendly label (e.g. "bar 版") next to a persona's prompt version.
     */
    get: operations["list_prompt_labels"];
  };
  "/v1beta/prompt-labels/{promptHash}": {
    /**
     * Names an identity hash, or clears its name when the label is blank. Idempotent
     * (PUT), keyed by the full hash the client already holds from the persona.
     */
    put: operations["set_prompt_label"];
  };
  "/v1beta/usage": {
    /**
     * Cumulative LLM usage: requests, tokens, cache-hit ratio, estimated cost, and
     * the same totals per model. Cost is always an estimate.
     */
    get: operations["usage"];
  };
  "/v1beta/usage/by-persona": {
    /**
     * The same usage broken down by persona, highest total tokens first. Unscoped,
     * it also includes the synthetic `system` bucket (compression, suggestions).
     */
    get: operations["usage_by_persona"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AccessToken: {
      accessToken: string;
    };
    /**
     * @description One account, as admin sees it: its opaque id and its login name. Never
     * carries a password or its hash. `account_id` is what [`UpdateAccountRequest`]
     * targets via `PATCH /accounts/{account_id}`.
     */
    AccountSummary: {
      accountId: string;
      username: string;
    };
    /**
     * @description A debug record of one agent inference: exactly the system + context the
     * character's model received, what it decided, and the tokens it cost. Streamed
     * live as a `debug` SSE frame and available in bulk for panel hydration.
     */
    AgentTrace: {
      /** @description The chosen action: `speak` | `speakWithMood` | `mood` | `read`. */
      action: string;
      /** @description The conversation/context text the agent read (the "public" messages). */
      conversation: string;
      /**
       * Format: int64
       * @description Wall-clock time the brain call took, in milliseconds.
       */
      durationMs?: number | null;
      estimatedCost?: null | components["schemas"]["Cost"];
      groupId: string;
      /** @description The spoken line, when it spoke. */
      message?: string | null;
      /**
       * @description The model that produced this inference (e.g. `gpt-4o-mini`); absent for
       * the mock brain, which runs no model.
       */
      model?: string | null;
      /** @description The mood, when it showed one. */
      mood?: string | null;
      personaId: string;
      personaName: string;
      /** @description The full system prompt the agent got (persona + variables + roster). */
      system: string;
      /** Format: int64 */
      ts: number;
      usage?: null | components["schemas"]["TokenUsage"];
    };
    /**
     * @description An RFC 9457 problem document — the body of every 4xx this API produces.
     *
     * Constructed through the named helpers below rather than field-by-field, so
     * the slug used for a given status is decided in exactly one place and can't
     * drift between handlers.
     */
    ApiError: {
      /**
       * @description The human-readable explanation of *this specific* occurrence — the
       * sentence that used to be the entire `text/plain` body. Safe to show a
       * user; never carries a secret, a stack trace, or a provider's raw
       * response.
       */
      detail?: string | null;
      /**
       * Format: int32
       * @description The HTTP status code, repeated in the body so a problem document stays
       * meaningful when it's logged or forwarded away from its response.
       */
      status: number;
      /**
       * @description The status code's canonical reason phrase (e.g. `Forbidden`) — a short
       * human summary of the problem *type*, not of this occurrence.
       */
      title: string;
      /**
       * @description Stable, machine-readable identifier for *what* went wrong, e.g.
       * `urn:agoralume:error:not-admin`. Match on this rather than on `detail`,
       * whose wording is free to change. Always present.
       * @example urn:agoralume:error:not-found
       */
      type: string;
    };
    /**
     * @description An estimated cost breakdown for the accumulated usage. Always an estimate:
     * rates are operator-supplied and providers/models differ, so the UI labels it
     * "for reference only".
     */
    Cost: {
      /**
       * Format: double
       * @description Cost of cached input tokens.
       */
      cachedInput: number;
      /** @description Currency label the rates are in (e.g. `USD`). */
      currency: string;
      /**
       * Format: double
       * @description Cost of fresh (non-cached) input tokens.
       */
      input: number;
      /**
       * Format: double
       * @description Cost of output tokens.
       */
      output: number;
      /**
       * Format: double
       * @description Sum of the above.
       */
      total: number;
    };
    /**
     * @description The `POST /accounts` request: the initial login for a brand-new account,
     * chosen by admin and communicated to whoever the account is for out of
     * band — there's no self-service registration or password-reset flow.
     */
    CreateAccountRequest: {
      password: string;
      username: string;
    };
    /**
     * @description Cumulative LLM usage across the whole server (since first run, when
     * persisted; since startup otherwise) — the global "total usage" view.
     * `GET /usage`.
     */
    DebugUsage: {
      /**
       * Format: double
       * @description Cached prompt tokens ÷ prompt tokens, in `0.0..=1.0`; `0` before any
       * usage is seen. How much the cache is saving.
       */
      cacheHitRatio: number;
      /** Format: int64 */
      cachedPromptTokens: number;
      /** Format: int64 */
      completionTokens: number;
      estimatedCost?: null | components["schemas"]["Cost"];
      /**
       * @description The same totals broken down by model, largest (by total tokens) first.
       * Empty until the first inference is recorded.
       */
      models?: components["schemas"]["ModelUsage"][];
      /** Format: int64 */
      promptTokens: number;
      /**
       * Format: int64
       * @description Number of agent inferences (LLM requests in LLM mode).
       */
      requests: number;
      /** Format: int64 */
      totalTokens: number;
    };
    /**
     * @description A sub-unit inside an organization; its variables sit between the org's and
     * the persona's in the inheritance chain.
     */
    Department: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name: string;
      organizationId: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /** @description A partial Department: only the properties present are merged. `id` is ignored. */
    DepartmentPatch: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name?: string;
      organizationId?: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /** @description The body of an environment-event request. */
    EventBody: {
      /** @description What changed, e.g. "It starts to rain." */
      description: string;
      /**
       * @description Urgent events preempt the current turn; ordinary ones fold into the
       * context at the next agent boundary.
       */
      urgent?: boolean;
    };
    /**
     * @description A chat room: the AI personas that may speak, plus the user identity that
     * represents "you" here.
     */
    Group: {
      id?: string;
      name: string;
      personaIds: string[];
      selfPersonaId: string;
    };
    /** @description A partial Group: only the properties present are merged. `id` is ignored. */
    GroupPatch: {
      id?: string;
      name?: string;
      personaIds?: string[];
      selfPersonaId?: string;
    };
    /**
     * @description Conversation-starter suggestions for a group: a few short first-person
     * messages the user could send next when they aren't sure what to say. Generated
     * server-side and cached (and persisted) so they aren't recomputed on every
     * open — the frontend only fetches and displays them. Time-aware via
     * [`GroupSuggestions::time_of_day`] so an evening opener isn't offered in the
     * morning. `GET /groups/{id}/suggestions`.
     */
    GroupSuggestions: {
      /**
       * Format: int64
       * @description When these were generated (epoch ms); `0` before the first generation.
       */
      generatedAt: number;
      /**
       * @description The suggested opener lines, in the user's language. Empty until the first
       * generation for this group completes.
       */
      prompts: string[];
      /**
       * @description Id of the last conversation message present when these were generated — the
       * conversation-staleness key. Server bookkeeping the UI can ignore; absent
       * when the group had no messages yet.
       */
      throughId?: string | null;
      /**
       * @description The coarse time-of-day bucket the suggestions were tuned for
       * (`morning` / `afternoon` / `evening` / `night`) — lets the server tell when
       * they've gone stale against the clock, and the UI hint the framing.
       */
      timeOfDay?: string;
    };
    /**
     * @description One model a provider's listing endpoint reported. `name` is a display label
     * when the provider offers one (Gemini does; OpenAI-compatible listings
     * usually don't), never required for choosing the model — `id` is what's
     * actually sent as `LlmSettings::model`.
     */
    LlmModelInfo: {
      id: string;
      name?: string | null;
    };
    /**
     * @description The `POST /llm/models` request: which endpoint to list models from. `apiKey`
     * is optional — omitted, the backend uses the currently-stored key, but only
     * when `baseUrl` matches the stored endpoint (see `routes::llm`), so this
     * can't be used to make the server send its stored credential to an arbitrary
     * third-party URL.
     */
    LlmModelsQuery: {
      apiKey?: string | null;
      baseUrl: string;
    };
    /** @description The `POST /llm/models` response. */
    LlmModelsView: {
      models: components["schemas"]["LlmModelInfo"][];
    };
    /**
     * @description A partial update to the LLM provider configuration — every field is
     * optional; an absent field leaves the current value alone. `baseUrl` /
     * `model` / `apiKey` treat an empty string as "clear this field", matching the
     * endpoint's other optional-string convention (there's never a reason to
     * *store* an empty string here). `pricing` with both rates at zero clears the
     * configured pricing (shows token counts only) rather than pinning a $0 rate.
     */
    LlmSettingsPatch: {
      /**
       * @description The new key, or `""` to clear it. Omit entirely to leave the stored key
       * untouched — the frontend must never send this unless the operator
       * actually typed a new value, or every unrelated settings save would wipe
       * the key.
       */
      apiKey?: string | null;
      baseUrl?: string | null;
      compressAfter?: number | null;
      compressKeep?: number | null;
      /** Format: int64 */
      compressMaxTokens?: number | null;
      enabled?: boolean | null;
      /** Format: int32 */
      maxRetries?: number | null;
      /** Format: int64 */
      maxRpm?: number | null;
      /** Format: int64 */
      maxTokens?: number | null;
      model?: string | null;
      pricing?: null | components["schemas"]["Pricing"];
      /** Format: int64 */
      retryBaseMs?: number | null;
    };
    /**
     * @description The `GET`/`PATCH /llm/settings` response: the live LLM provider
     * configuration, with the API key stripped to a presence flag. Built by hand
     * from [`crate::llm_config::LlmSettings`] (never derived by serializing it
     * directly) — that's the one place a leaked key would slip out.
     */
    LlmSettingsView: {
      baseUrl?: string | null;
      /**
       * @description Whether *this caller* may write this config (`PATCH /llm/settings`,
       * `POST /llm/models`) — admin-only today (see `CurrentAdmin` in
       * `backend/src/state.rs`), computed by the `GET /llm/settings` handler
       * from the caller's actual `Subject`, not by anything in this struct's
       * `From` impl (which always seeds it `false`, having no caller to ask).
       * The frontend keys its write controls off this field instead of
       * re-deriving "am I admin" from its own copy of the session role, so it
       * can't drift from whatever the server actually enforces.
       */
      canEdit: boolean;
      compressAfter: number;
      compressKeep: number;
      /** Format: int64 */
      compressMaxTokens: number;
      enabled: boolean;
      /**
       * @description Whether a key is currently stored. The key itself is never sent to a
       * client once saved.
       */
      hasApiKey: boolean;
      /** Format: int32 */
      maxRetries: number;
      /** Format: int64 */
      maxRpm: number;
      /** Format: int64 */
      maxTokens: number;
      model?: string | null;
      pricing?: null | components["schemas"]["Pricing"];
      /** Format: int64 */
      retryBaseMs: number;
    };
    LoginRequest: {
      password: string;
      /** @description The fixed admin login name, or a regular account's own username. */
      username: string;
    };
    /** @description The body of a sign-out request. */
    LogoutRequest: {
      /**
       * @description The session's refresh token, so it dies with the access token. Omitting
       * it leaves a token good for another 30 days alive, which is almost never
       * what a sign-out means.
       */
      refreshToken?: string | null;
    };
    /**
     * @description One persona-scoped memory: a fact a character chose to remember. Tagged with
     * the persona identity hash ([`Persona::prompt_hash`]) that was in force when it
     * was written, so a later rewrite of the persona never recalls a previous
     * version's memories out of character. Persisted in the workspace snapshot
     * alongside the personas the memories belong to.
     */
    Memory: {
      content: string;
      /**
       * Format: int64
       * @description Milliseconds since the Unix epoch when the memory was written.
       */
      createdAt: number;
      id: string;
      personaId: string;
      /**
       * @description The persona identity hash in force when this memory was written — the
       * scope key that keeps recall in-character. Always a real hash: a persona
       * with no prompt (no hash) can hold no memories.
       */
      promptHash: string;
    };
    /** @description Request body for writing a memory: just the text to remember. */
    MemoryInput: {
      content: string;
    };
    /** @description One chat line. Tagged by `kind`, matching the TypeScript `Message` union. */
    Message: OneOf<[{
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "conversation";
      personaId: string;
      /** @description AI persona ids that have successfully processed (read) this message. */
      readBy?: string[] | null;
      streaming?: boolean | null;
      text: string;
      /** Format: int64 */
      ts: number;
    }, {
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "mood";
      mood: string;
      note?: string | null;
      personaId: string;
      /** Format: int64 */
      ts: number;
    }, {
      groupId: string;
      id: string;
      /** @enum {string} */
      kind: "system";
      personaId: string;
      /**
       * @description The status's canonical reason (e.g. "Too Many Requests"), or a short
       * generic label for a transport failure with no status.
       */
      reason: string;
      /**
       * Format: int32
       * @description The HTTP status code, when the failure carried one (e.g. 429).
       */
      status?: number | null;
      /** Format: int64 */
      ts: number;
    }]>;
    /**
     * @description One model's slice of the cumulative usage — e.g. after switching providers
     * or models mid-run, each keeps its own running total rather than blending
     * into a single undifferentiated number. Part of [`DebugUsage::models`].
     */
    ModelUsage: {
      /** Format: int64 */
      cachedPromptTokens: number;
      /** Format: int64 */
      completionTokens: number;
      estimatedCost?: null | components["schemas"]["Cost"];
      /**
       * @description The model name (e.g. `gpt-4o-mini`), or `"unknown"` for traces from a
       * brain that runs no real model (the rule-based mock).
       */
      model: string;
      /** Format: int64 */
      promptTokens: number;
      /** Format: int64 */
      requests: number;
      /** Format: int64 */
      totalTokens: number;
    };
    /**
     * @description A bucket for classifying personas that also carries shared template
     * variables its members inherit.
     */
    Organization: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /** @description A partial Organization: only the properties present are merged. `id` is ignored. */
    OrganizationPatch: {
      blurb?: string | null;
      color?: string | null;
      id?: string;
      name?: string;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description A user identity or an AI agent. AI personas carry the system prompt and
     * variables the model needs; user personas are just a "you" to speak as.
     */
    Persona: {
      avatarUrl?: string | null;
      blurb?: string | null;
      color: string;
      departmentId?: string | null;
      emoji?: string | null;
      gradient?: string | null;
      id?: string;
      kind: components["schemas"]["PersonaKind"];
      name: string;
      organizationId?: string | null;
      /**
       * @description Content hash of the raw `system_prompt` template — the persona's identity
       * "version". Server-computed and effectively read-only on the wire: it is
       * recomputed on every create/update (and on load) and any value a client
       * sends is ignored. `None` when there is no prompt (user identities). Full
       * lowercase-hex SHA-256; the UI shows a truncated prefix. See [`prompt_hash`].
       */
      promptHash?: string | null;
      systemPrompt?: string | null;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description The two persona roles: a user's own identity vs. an AI agent.
     * @enum {string}
     */
    PersonaKind: "user" | "ai";
    /** @description A partial Persona: only the properties present are merged. `id` is ignored. */
    PersonaPatch: {
      avatarUrl?: string | null;
      blurb?: string | null;
      color?: string;
      departmentId?: string | null;
      emoji?: string | null;
      gradient?: string | null;
      id?: string;
      kind?: components["schemas"]["PersonaKind"];
      name?: string;
      organizationId?: string | null;
      /**
       * @description Content hash of the raw `system_prompt` template — the persona's identity
       * "version". Server-computed and effectively read-only on the wire: it is
       * recomputed on every create/update (and on load) and any value a client
       * sends is ignored. `None` when there is no prompt (user identities). Full
       * lowercase-hex SHA-256; the UI shows a truncated prefix. See [`prompt_hash`].
       */
      promptHash?: string | null;
      systemPrompt?: string | null;
      variables?: {
        [key: string]: string;
      } | null;
    };
    /**
     * @description One persona's own slice of a usage total — a further breakdown by which
     * character is driving the spend. Serves both `GET
     * /usage/by-persona?groupId=…` (one group's [`DebugUsage`]) and the
     * site-wide `GET /usage/by-persona` (summed across every group).
     */
    PersonaUsage: {
      personaId: string;
      usage: components["schemas"]["DebugUsage"];
    };
    /**
     * @description Token pricing used to turn usage into an estimated cost. Rates are per
     * 1,000,000 tokens, in `currency`. A rough operator-supplied estimate — models
     * and providers differ — so the UI always labels the result "for reference".
     * Doubles as a wire type (`GET`/`PATCH /llm/settings`), hence `camelCase`; the
     * one place that reads a little unusual is its own corner of `llm.toml`.
     */
    Pricing: {
      /**
       * Format: double
       * @description Price per 1M cached input tokens. Usually cheaper than fresh input;
       * defaults to the fresh input rate when not set (a conservative estimate
       * that shows no cache saving until a discounted rate is provided).
       */
      cachedInputPerM: number;
      /** @description Currency label the rates are quoted in. */
      currency: string;
      /**
       * Format: double
       * @description Price per 1M fresh (non-cached) input tokens.
       */
      inputPerM: number;
      /**
       * Format: double
       * @description Price per 1M output tokens.
       */
      outputPerM: number;
    };
    /**
     * @description A user-assigned, git-tag-style name for a persona identity hash
     * ([`Persona::prompt_hash`]). Held in a side table so naming a version never
     * mutates the persona itself; content-addressing means reverting to earlier
     * exact prompt text resolves back to the same (possibly already-named) hash.
     */
    PromptLabel: {
      hash: string;
      label: string;
    };
    /** @description Request body for naming a prompt identity hash. A blank label clears the name. */
    PromptLabelInput: {
      label: string;
    };
    /**
     * @description A single AI persona acknowledging it successfully processed a message —
     * whether or not it chose to reply (agents may read without replying).
     */
    ReadReceipt: {
      groupId: string;
      messageId: string;
      personaId: string;
    };
    RefreshRequest: {
      refreshToken: string;
    };
    /** @description The body of a send request. */
    SendBody: {
      /**
       * @description Which user identity to author as; must be a `user` persona, not an AI
       * one. Omitted, the group's `selfPersonaId` is used.
       */
      personaId?: string | null;
      /** @description The message text. */
      text: string;
    };
    /**
     * @description What the running server offers — lets the client tell a mock build (no LLM,
     * in-memory only) apart from a production one, independently of whether the
     * server is reachable at all.
     */
    ServerMeta: {
      /**
       * @description Whether a client must log in (`POST /auth/login`) before anything
       * else works — false under mock mode or `AGORALUME_AUTH_DISABLED`, in
       * which case every request resolves to the bootstrap account with no
       * token at all. Independent of `mock`/`llm`: a persistent server with
       * no real model wired in still enforces login.
       */
      authRequired: boolean;
      /** @description An LLM is wired in to generate replies. */
      llm: boolean;
      /**
       * @description No LLM and no persistence — the "mock" mode. Equivalent to
       * `!llm && !persistent`.
       */
      mock: boolean;
      /** @description State is persisted and survives a restart. */
      persistent: boolean;
      /** @description Server crate version. */
      version: string;
    };
    /** @description User-level preferences. */
    Settings: {
      /** Format: int32 */
      chatFontSize: number;
      nativeLanguage: string;
      uiLanguage: string;
    };
    /** @description A partial Settings: only the properties present are merged. `id` is ignored. */
    SettingsPatch: {
      /** Format: int32 */
      chatFontSize?: number;
      nativeLanguage?: string;
      uiLanguage?: string;
    };
    TokenPair: {
      /** @description Short-lived; sent as `Authorization: Bearer <token>` on every request. */
      accessToken: string;
      /**
       * @description Long-lived; used only against `POST /auth/refresh` to mint a fresh
       * access token without asking for the password again.
       */
      refreshToken: string;
      /**
       * @description `"admin"` or `"account"` — which kind of session this token belongs
       * to, so the frontend can route an admin session to its own dashboard
       * instead of a workspace it doesn't have. A UX routing hint only, not
       * itself a permission grant: every route still checks the token's
       * actual `Subject` server-side regardless of what this field says.
       */
      role: string;
    };
    /**
     * @description Token usage for one LLM inference. Zero across the board when the provider
     * reports nothing; entirely absent (on the trace) for the rule-based mock,
     * which makes no LLM call.
     */
    TokenUsage: {
      /**
       * Format: int64
       * @description Of the prompt tokens, how many were served from the provider's cache —
       * billed cheaper. The basis for the cache-hit ratio and cache savings.
       */
      cachedPromptTokens: number;
      /**
       * Format: int64
       * @description Output ("completion") tokens billed for this call.
       */
      completionTokens: number;
      /**
       * Format: int64
       * @description Input ("prompt") tokens billed for this call.
       */
      promptTokens: number;
      /**
       * Format: int64
       * @description Total tokens the provider reported (or input+output when it only gives
       * the two).
       */
      totalTokens: number;
    };
    /**
     * @description A processing round: what triggered it and how far each AI member has got.
     * Owned by the backend and streamed independently of message history (a named
     * `turn` SSE frame, seeded on connect), so the pinned progress bar reflects the
     * *current* processing state whether or not the trigger line is in the loaded
     * window — and shows progress for event triggers that have no user message at
     * all. `active` tracks whether the coordinator is still running the round.
     */
    Turn: {
      /** @description Whether the coordinator is still running this turn. */
      active: boolean;
      groupId: string;
      id: string;
      /**
       * @description The AI members participating, in the group's member order, each with its
       * progress this round.
       */
      members: components["schemas"]["TurnMember"][];
      /**
       * Format: int64
       * @description Epoch millis when the turn started.
       */
      startedAt: number;
      trigger: components["schemas"]["TurnTrigger"];
    };
    /** @description One AI member's progress within a turn. */
    TurnMember: {
      personaId: string;
      /**
       * @description The id of this member's first reply line this turn — the avatar's jump
       * target. Present only once `state` is `replied`.
       */
      replyId?: string | null;
      state: components["schemas"]["TurnMemberState"];
    };
    /**
     * @description How far one AI member has got in the current turn — the buckets the pinned
     * progress bar tints avatars by. Mirrors a read receipt's meaning but is
     * turn-scoped rather than message-scoped, so it works for an event trigger that
     * has no message to hang a receipt on.
     * @enum {string}
     */
    TurnMemberState: "pending" | "read" | "replied";
    /**
     * @description What kicked off a turn: a conversation line someone sent, or an environment
     * event that carries no message of its own. Tagged by `kind` to match the
     * TypeScript union.
     */
    TurnTrigger: OneOf<[{
      /** @enum {string} */
      kind: "message";
      messageId: string;
      personaId: string;
      text: string;
    }, {
      /** @enum {string} */
      kind: "event";
      label: string;
    }]>;
    /**
     * @description The `PATCH /accounts/{account_id}` request: admin changing an existing
     * account's login — its username, its password, or both. Both fields are
     * optional and independent (`None` leaves that field untouched); an empty
     * patch is a harmless no-op. There's still no self-service path — this is
     * admin editing *someone else's* login, not an account changing its own.
     */
    UpdateAccountRequest: {
      password?: string | null;
      username?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Every existing account, for the admin dashboard's account list. */
  list_accounts: {
    responses: {
      /** @description Every account's id and login name; never a password */
      200: {
        content: {
          "application/json": components["schemas"]["AccountSummary"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Provisions a brand-new account with an admin-chosen username and
   * password. There's no self-service registration — this is the only way an
   * account gets created.
   */
  create_account: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAccountRequest"];
      };
    };
    responses: {
      /** @description The created account */
      201: {
        content: {
          "application/json": components["schemas"]["AccountSummary"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Empty/reserved/taken username, empty password, or no persistent backend */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Changes an existing account's username, password, or both. Every live
   * session for that account is revoked: its tokens stop working immediately and
   * the holder must sign in again.
   */
  update_account: {
    parameters: {
      path: {
        /** @description The account to edit */
        accountId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountRequest"];
      };
    };
    responses: {
      /** @description The updated account; its sessions are revoked */
      200: {
        content: {
          "application/json": components["schemas"]["AccountSummary"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown id, empty/reserved/taken username, empty password, or no persistent backend */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Logs in as the admin (username `"admin"`) or a regular account (its own
   * stored username). An account with no fixed password yet accepts this
   * boot's generated one instead — see the server log at startup.
   */
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description A fresh token pair and the session's role */
      200: {
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Unknown username or wrong password (not distinguished) */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Ends the current session: the presented access token (from the
   * `Authorization` header) and refresh token stop working immediately.
   */
  logout: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequest"];
      };
    };
    responses: {
      /** @description Signed out (idempotent) */
      204: {
        content: never;
      };
    };
  };
  /**
   * Mints a fresh access token from a still-valid refresh token, without
   * asking for the password again. The refresh token itself is not rotated —
   * it keeps working until its own (much longer) expiry.
   */
  refresh: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description A fresh access token; the refresh token is unchanged */
      200: {
        content: {
          "application/json": components["schemas"]["AccessToken"];
        };
      };
      /** @description Unknown, expired, revoked, or not a refresh token */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Every department in the workspace, across all organizations. */
  list_depts: {
    responses: {
      /** @description Every department, across all organizations */
      200: {
        content: {
          "application/json": components["schemas"]["Department"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Creates a department. */
  create_dept: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Department"];
      };
    };
    responses: {
      /** @description The created department */
      201: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** One department by id. */
  get_dept: {
    parameters: {
      path: {
        /** @description The department to read */
        departmentId: string;
      };
    };
    responses: {
      /** @description The department */
      200: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown department */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Deletes a department. */
  delete_dept: {
    parameters: {
      path: {
        /** @description The department to delete */
        departmentId: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown department */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Merges a partial update onto a department. */
  update_dept: {
    parameters: {
      path: {
        /** @description The department to update */
        departmentId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DepartmentPatch"];
      };
    };
    responses: {
      /** @description The updated department */
      200: {
        content: {
          "application/json": components["schemas"]["Department"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown department */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Malformed patch */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Every chat group in the workspace. */
  list_groups: {
    responses: {
      /** @description Every group */
      200: {
        content: {
          "application/json": components["schemas"]["Group"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Creates a group. */
  create_group: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Group"];
      };
    };
    responses: {
      /** @description The created group */
      201: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** One group by id. */
  get_group: {
    parameters: {
      path: {
        /** @description The group to read */
        groupId: string;
      };
    };
    responses: {
      /** @description The group */
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Deletes a group. */
  delete_group: {
    parameters: {
      path: {
        /** @description The group to delete */
        groupId: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Merges a partial update onto a group. */
  update_group: {
    parameters: {
      path: {
        /** @description The group to update */
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GroupPatch"];
      };
    };
    responses: {
      /** @description The updated group */
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Malformed patch */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Posts an environment event — rain, time passing, an emergency — letting the
   * world outside the chat influence the agents. Its effect arrives on the SSE
   * stream.
   */
  post_event: {
    parameters: {
      path: {
        /** @description The group to post the event into */
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventBody"];
      };
    };
    responses: {
      /** @description Queued */
      202: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Blank or over-long description */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * A contiguous window of message history, oldest first. Max 500 lines (160
   * without an `anchor`).
   */
  list_messages: {
    parameters: {
      query?: {
        /** @description Line id to centre the window on. Omitted, the window ends at the newest line. */
        anchor?: string | null;
        /** @description Lines before the anchor (or before the tail). Clamped to 500. */
        before?: number | null;
        /** @description Lines after the anchor. Ignored without an `anchor`. Clamped to 500. */
        after?: number | null;
        /**
         * @description Read mark (epoch ms). Without an `anchor`, widens the window back to cover
         * every unread line.
         */
        since?: number | null;
      };
      path: {
        /** @description The group whose history to read */
        groupId: string;
      };
    };
    responses: {
      /** @description The window, oldest first; empty for an unknown group */
      200: {
        content: {
          "application/json": components["schemas"]["Message"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Posts a user message and starts the agents' turn. Replies, moods, and read
   * receipts arrive on the SSE stream.
   */
  send_message: {
    parameters: {
      path: {
        /** @description The group to post into */
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendBody"];
      };
    };
    responses: {
      /** @description The stored message */
      200: {
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Blank or over-long text, or a `personaId` that is not a user identity */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Resumes a turn suspended by a failed agent inference. A no-op if nothing is
   * suspended. Its effect arrives on the SSE stream.
   */
  retry_turn: {
    parameters: {
      path: {
        /** @description The group whose suspended turn to resume */
        groupId: string;
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Server-Sent Events for a group.
   * @description Frames: unnamed = `Message`; `read` = `ReadReceipt`; `activity` =
   * `{ "active": bool }`; `turn` = `Turn`; `debug` = `AgentTrace`;
   * `suggestions` = `GroupSuggestions`. `activity` and `turn` are seeded on connect.
   */
  stream: {
    parameters: {
      path: {
        /** @description The group to stream */
        groupId: string;
      };
    };
    responses: {
      /** @description An open event stream */
      200: {
        content: {
          "text/event-stream": unknown;
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Cached conversation-starter suggestions, served from the server-side cache.
   * Empty (`generatedAt == 0`) until the first generation completes.
   */
  get_suggestions: {
    parameters: {
      path: {
        /** @description The group whose suggestions to read */
        groupId: string;
      };
    };
    responses: {
      /** @description The cached suggestions; a refresh may follow on the stream */
      200: {
        content: {
          "application/json": components["schemas"]["GroupSuggestions"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Creates a fresh set of suggestions (the composer's "give me other ideas").
   * Generated in the background; the result arrives on the `suggestions` SSE
   * frame. Rate-limited server-side — repeated calls coalesce.
   */
  regenerate_suggestions: {
    parameters: {
      path: {
        /** @description The group to regenerate suggestions for */
        groupId: string;
      };
    };
    responses: {
      /** @description Accepted, or coalesced with a recent one */
      202: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Recent agent traces: the prompt each character received and what it decided.
   * Live updates arrive as `debug` SSE frames.
   */
  list_traces: {
    parameters: {
      path: {
        /** @description The group whose traces to read */
        groupId: string;
      };
    };
    responses: {
      /** @description Traces, oldest first */
      200: {
        content: {
          "application/json": components["schemas"]["AgentTrace"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown group */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Liveness probe, for an orchestrator rather than the app. */
  health: {
    responses: {
      /** @description Up; the body is the literal `ok` */
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  /**
   * Lists the models a provider endpoint offers, so the model field can be a
   * picker. Admin-only. `apiKey` is required unless `baseUrl` matches the
   * already-configured endpoint.
   */
  list_llm_models: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LlmModelsQuery"];
      };
    };
    responses: {
      /** @description The models that endpoint reports */
      200: {
        content: {
          "application/json": components["schemas"]["LlmModelsView"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Empty or non-HTTP(S) baseUrl, no usable key, or the endpoint refused */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * The live LLM provider configuration. Any signed-in caller may read it;
   * `canEdit` says whether this caller may write it.
   */
  get_llm_settings: {
    responses: {
      /** @description The live configuration; the API key is reduced to `hasApiKey` */
      200: {
        content: {
          "application/json": components["schemas"]["LlmSettingsView"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Merges a partial update onto the LLM provider configuration and applies it
   * immediately. Admin-only.
   */
  update_llm_settings: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LlmSettingsPatch"];
      };
    };
    responses: {
      /** @description Applied and persisted to llm.toml; no restart needed */
      200: {
        content: {
          "application/json": components["schemas"]["LlmSettingsView"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description The resulting configuration would not build; nothing changed */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** The server's mode: mock build (no LLM, in-memory) vs. production. */
  meta: {
    responses: {
      /** @description Server capabilities and mode */
      200: {
        content: {
          "application/json": components["schemas"]["ServerMeta"];
        };
      };
    };
  };
  /** Every organization in the workspace. */
  list_orgs: {
    responses: {
      /** @description Every organization */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Creates an organization. */
  create_org: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
    responses: {
      /** @description The created organization */
      201: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** One organization by id. */
  get_org: {
    parameters: {
      path: {
        /** @description The organization to read */
        organizationId: string;
      };
    };
    responses: {
      /** @description The organization */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown organization */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Deletes an organization, cascading to its departments. */
  delete_org: {
    parameters: {
      path: {
        /** @description The organization to delete */
        organizationId: string;
      };
    };
    responses: {
      /** @description Deleted, cascading to its departments */
      204: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown organization */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Merges a partial update onto an organization. */
  update_org: {
    parameters: {
      path: {
        /** @description The organization to update */
        organizationId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationPatch"];
      };
    };
    responses: {
      /** @description The updated organization */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown organization */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Malformed patch */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Every persona in the workspace — the one user identity and every AI agent. */
  list_personas: {
    responses: {
      /** @description Every persona */
      200: {
        content: {
          "application/json": components["schemas"]["Persona"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Creates a persona. Names are globally unique, and there is only ever one
   * user identity ("you"), so either collision is refused with 409.
   */
  create_persona: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Persona"];
      };
    };
    responses: {
      /** @description The created persona */
      201: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Name taken, or a second user identity */
      409: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** One persona by id. */
  get_persona: {
    parameters: {
      path: {
        /** @description The persona to read */
        personaId: string;
      };
    };
    responses: {
      /** @description The persona */
      200: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown persona */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Deletes a persona. The last remaining user identity can't go — every group
   * still needs a "you".
   */
  delete_persona: {
    parameters: {
      path: {
        /** @description The persona to delete */
        personaId: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown persona */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Refused: the last user identity */
      409: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Merges a partial update onto a persona. `promptHash` is recomputed from the
   * resulting prompt; any value sent for it is ignored.
   */
  update_persona: {
    parameters: {
      path: {
        /** @description The persona to update */
        personaId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PersonaPatch"];
      };
    };
    responses: {
      /** @description The updated persona */
      200: {
        content: {
          "application/json": components["schemas"]["Persona"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown persona */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Name taken, or a second user identity */
      409: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Malformed patch */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Every memory a persona has accumulated, across all of its identity versions,
   * newest first. The memory-management UI groups the result by `promptHash`/label.
   */
  list_memories: {
    parameters: {
      path: {
        /** @description The persona whose memories to list */
        personaId: string;
      };
    };
    responses: {
      /** @description Every memory, newest first */
      200: {
        content: {
          "application/json": components["schemas"]["Memory"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown persona */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Writes a memory for a persona, tagged with its current identity hash. */
  create_memory: {
    parameters: {
      path: {
        /** @description The persona to remember this for */
        personaId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemoryInput"];
      };
    };
    responses: {
      /** @description The created memory */
      201: {
        content: {
          "application/json": components["schemas"]["Memory"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown persona */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description The persona has no prompt to scope a memory to, or blank content */
      409: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Deletes one of a persona's memories. */
  delete_memory: {
    parameters: {
      path: {
        /** @description The persona the memory belongs to */
        personaId: string;
        /** @description The memory to delete */
        memoryId: string;
      };
    };
    responses: {
      /** @description Deleted */
      204: {
        content: never;
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown memory for that persona */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** The signed-in account's own display preferences. */
  get_preferences: {
    responses: {
      /** @description This account's preferences */
      200: {
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /** Merges a partial update onto the account's preferences. */
  update_preferences: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsPatch"];
      };
    };
    responses: {
      /** @description The updated preferences */
      200: {
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Malformed patch */
      422: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * All user-assigned names for persona identity hashes. The memory UI reads this
   * to show a friendly label (e.g. "bar 版") next to a persona's prompt version.
   */
  list_prompt_labels: {
    responses: {
      /** @description Every named identity hash */
      200: {
        content: {
          "application/json": components["schemas"]["PromptLabel"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Names an identity hash, or clears its name when the label is blank. Idempotent
   * (PUT), keyed by the full hash the client already holds from the persona.
   */
  set_prompt_label: {
    parameters: {
      path: {
        /** @description The full persona identity hash to name */
        promptHash: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromptLabelInput"];
      };
    };
    responses: {
      /** @description The stored label; empty when cleared */
      200: {
        content: {
          "application/json": components["schemas"]["PromptLabel"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * Cumulative LLM usage: requests, tokens, cache-hit ratio, estimated cost, and
   * the same totals per model. Cost is always an estimate.
   */
  usage: {
    parameters: {
      query?: {
        /** @description One group only. Omitted, covers the whole account. */
        groupId?: string | null;
      };
    };
    responses: {
      /** @description Usage for the requested scope */
      200: {
        content: {
          "application/json": components["schemas"]["DebugUsage"];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown `groupId` */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
  /**
   * The same usage broken down by persona, highest total tokens first. Unscoped,
   * it also includes the synthetic `system` bucket (compression, suggestions).
   */
  usage_by_persona: {
    parameters: {
      query?: {
        /** @description One group only. Omitted, covers the whole account. */
        groupId?: string | null;
      };
    };
    responses: {
      /** @description One entry per persona */
      200: {
        content: {
          "application/json": components["schemas"]["PersonaUsage"][];
        };
      };
      /** @description Not signed in */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Not permitted for this identity */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
      /** @description Unknown `groupId` */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ApiError"];
        };
      };
    };
  };
}
